# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/CSEE4280/The-FPGA-Programming-Handbook-Second-Edition/CH5/xdc/calculator_a7100t.xdc

# IP: C:/CSEE4280/The-FPGA-Programming-Handbook-Second-Edition/CH5/IP/sys_pll/sys_pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_pll || ORIG_REF_NAME==sys_pll} -quiet] -quiet
